/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WlGdFXLOGQX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "../components/ui/card"
import { Button } from "../components/ui/button"
import { Label } from "../components/ui/label"
import { Input } from "../components/ui/input"
import poppins from "../font/font"
import React from "react"

export function PaymentLayout() {
  return (
    <Card className={`${poppins.className} bg-white`} style={{width:800,height:500}}>
      <CardHeader className="flex justify-between">
        <CardTitle className="">Add New Card</CardTitle>
        <Button className="text-muted-foreground" variant="ghost">
          <PanelBottomCloseIcon className="w-4 h-4" />
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="card-number">Card Number</Label>
          <div className="flex items-center space-x-3">
            <CreditCardIcon className="w-5 h-5 text-red-500" />
            <Input defaultValue="1234 0000 0000 0000" id="card-number" placeholder="1234 0000 0000 0000"/>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="name-on-card">Name on card</Label>
            <Input defaultValue="Daniyal" id="name-on-card" placeholder="Name on card" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="cvv">CVV</Label>
            <Input defaultValue="***" id="cvv" placeholder="***" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="expiry">Expiry</Label>
          <Input defaultValue="06/2024" id="expiry" placeholder="MM/YYYY" />
        </div>
      </CardContent>
      <CardFooter className="flex justify-between">
        <Button variant="outline">Pay Now</Button>
        <Button variant="outline">Cancel</Button>
      </CardFooter>
    </Card>
  )
}

function CreditCardIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}


function PanelBottomCloseIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M3 15h18" />
      <path d="m15 8-3 3-3-3" />
    </svg>
  )
}
